# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: linux-build
    env:
    - CGO_ENABLED=1
    goos:
    - linux
    ignore:
    - goos: linux
      goarch: 386
    - goos: linux
      goarch: arm
  - id: darwin-build
    ldflags:
    - -s
    env:
    - CGO_ENABLED=1
    - CC=/home/runner/work/osxcross/target/bin/o64-clang
    - CXX=/home/runner/work/osxcross/target/bin/o64-clang++
    goos:
    - darwin
    ignore:
    - goos: darwin
      goarch: 386
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
