name: Upload PNG
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  test:
    name: Upload PNG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run redash-visualizer
        run: |
          run-redash/run-redash.sh
          export PGPASSWORD=password
          API_KEY=`psql postgres://postgres:password@localhost:5432/postgres -c "select api_key from users where name='root_user'" -t -A`
          go run main.go run --host localhost:5000 --api-key $API_KEY --file graph_pr.png
      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: graph
          path: graph_pr.png